version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: estate_prod_api
    container_name: estate_prod_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start
    networks:
      - estate_prod_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: estate_prod_postgres
    container_name: estate_prod_postgres
    ports:
      - "5432:5432"
    volumes:
      - estate_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - estate_prod_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: estate_prod_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - estate_prod_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - estate_prod_nw

networks:
  estate_prod_nw:
    external: true

volumes:
  estate_prod_postgres_data: {}
  estate_prod_mailpit_data: {}


